// Code generated by "stringer -type=Action"; DO NOT EDIT.

package hand

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Blind-1]
	_ = x[Check-2]
	_ = x[Fold-3]
	_ = x[Call-4]
	_ = x[Raise-5]
}

const _Action_name = "UndefinedBlindCheckFoldCallRaise"

var _Action_index = [...]uint8{0, 9, 14, 19, 23, 27, 32}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
